#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 16 ConfigMap 
# Url: https://ithelp.ithome.com.tw/articles/10193935
# Licence: MIT
#####################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigyaml
data:
  k1: v1
  k2: v2
